const USER_SIGNIN = "USER_SIGNIN";
const USER_SIGNOUT = "USER_SIGNOUT";
const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";
const TOGGLE_MUTE = "TOGGLE_MUTE";

export {
  USER_SIGNIN,
  USER_SIGNOUT,
  ADD_TO_FAVOURITES,
  REMOVE_FROM_FAVOURITES,
  TOGGLE_MUTE,
};
