const USER_SIGNIN = "USER_SIGNIN";
const USER_SIGNOUT = "USER_SIGNOUT";
const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
const TOGGLE_MUTE = "TOGGLE_MUTE";

export { USER_SIGNIN, USER_SIGNOUT, ADD_TO_FAVORITES, TOGGLE_MUTE };
